### ISSUE TITLE
[API] Solo, vegetação e relevo não estão sendo salvos

### ISSUE THREAD

**Issue by edvaldoszy** [utfpr/hcf-api#35]
Ao cadastrar um novo tombo, embora o painel esteja enviando as informações de solo, relevo e vegetação, a API não está salvando as informações.

![Image](https://github.com/utfpr/hcf-api/assets/3211168/b2c2e99d-db19-456b-9dc3-9331f62eedd3)

---

## Acceptance criteria

| # | Given                                    | When                                                                      | Then                                                                                             |
|---|------------------------------------------|---------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|
| 1 | O usuário está cadastrando um novo tombo | Qualquer um dos campos "Solo", "Relevo" ou "Vegetação" for preenchido     | A API deve salvar as informações corretamente no banco para consulta posterior                   |
| 2 | O usuário está cadastrando um novo tombo | Qualquer um dos campos "Solo", "Relevo" ou "Vegetação" não for preenchido | A API não deve impedir o tombo de ser cadastrado, mantendo os valores não preenchidos como nulos |

**Comment by RyanRamos01** [comment]
Dando get no tombo criado, temos em local_coleta, o solo, relevo e vegetação inseridos, o problema pode estar no frontend?

![Image](https://github.com/utfpr/hcf-api/assets/49281976/101d55ae-9368-4eea-93e4-a31b6a766e2e)

**Comment by edvaldoszy** [comment]
Acabei de testar no front e está funcionando normalmente. Ontem eu aprovei um PR da Elaine, isso pode ter corrigido o problema. Vamos considerar o ticket como resolvido.

Abaixo está a requisição que o front-end fez.

```shell
curl 'https://api.hcf.cm.utfpr.edu.br/tombos' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en,pt-BR;q=0.9,pt;q=0.8,en-US;q=0.7' \
  -H 'content-type: application/json' \
  -H 'origin: https://hcf.cm.utfpr.edu.br' \
  -H 'priority: u=1, i' \
  -H 'referer: https://hcf.cm.utfpr.edu.br/' \
  -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkN1cmFkb3IiLCJlbWFpbCI6ImVkdmFsZG9zenlAZ21haWwuY29tIiwidGlwb191c3VhcmlvX2lkIjoxLCJpYXQiOjE3MTY0MDY1ODAsImV4cCI6MTcxNjU3OTM4MH0.xdwG8vBl0JXBqghK85lqyfwQIPwELWfsoPD1LCAhwjY' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
  --data-raw $'{"json":{"principal":{"nome_popular":"Nome popular 4","entidade_id":2,"numero_coleta":140214,"data_coleta":{"dia":1,"mes":1,"ano":2024},"tipo_id":"3","cor":"VERMELHO"},"taxonomia":{"familia_id":"8","genero_id":"248"},"localidade":{"latitude":"48°56\'15,00\\"N","longitude":"48°56\'16,00\\"W","altitude":100,"cidade_id":4104303},"paisagem":{"solo_id":"10","relevo_id":"6","vegetacao_id":"20"},"identificacao":{"identificadores":["1"],"data_identificacao":{"dia":1,"mes":1,"ano":2024}},"coletores":[3071]}}'
```

**Comment by RyanRamos01** [comment]
Perfeito!
