### ISSUE TITLE
[API] Refatoração na migração e relações de coletores com o Tombo

### ISSUE THREAD

**Issue by edvaldoszy** [utfpr/hcf-api#37]
Com intuito de organizar e melhoras as relações do tombo com coletores, foi decidido fazer uma refatoração em como os registros são armazenados.

A partir de agora vamos somente o ID do coletor principal no tombo, os coletores complementares serão armazenados em um único campo de texto numa tabela chamada `coletores_complementares`.

O diagrama abaixo exemplifica como as tabelas vão ficar:

![image](https://github.com/utfpr/hcf-api/assets/3211168/544ae1aa-87da-4af7-b6ca-c5a3bd01e35f)

**Comment by RyanRamos01** [comment]
Hoje a relação de coletores com tombo é a seguinte:

![Image](https://github.com/utfpr/hcf-api/assets/49281976/673aac86-2f73-4d32-9d46-0d3bcac30627)

**Comment by RyanRamos01** [comment]
Nova modelagem:



![Image](https://github.com/utfpr/hcf-api/assets/49281976/870a0212-34ac-4e34-82fd-9df0bf601947)

**Comment by RyanRamos01** [comment]
Migração do banco ok!

**Comment by edvaldoszy** [comment]
@RyanRamos01 ficou faltando a tabela nova para os coletores complementares.

Segundo o que conversamos semana passada vamos criar uma tabela separada, só com o ID do tombo e um campo texto para os coletores complementares.

**Comment by RyanRamos01** [comment]
Novo formato:

![image](https://github.com/utfpr/hcf-api/assets/49281976/7f536d6b-5053-4aa7-95d5-cb0c998270ce)

![image](https://github.com/utfpr/hcf-api/assets/49281976/c3197971-ae26-42f6-b767-3a98e3034532)

**Comment by edvaldoszy** [comment]
@RyanRamos01 você não coloca o ID de "coletores_complementares" do tombo, e sim ao contrário, o ID do tombo em "coletores_complementares"

**Comment by RyanRamos01** [comment]
Feito

![Image](https://github.com/utfpr/hcf-api/assets/49281976/d7bd332d-f04c-48a8-905e-4741583a9e45)

**Comment by edvaldoszy** [comment]
Agora sim!!
