### ISSUE TITLE
[API] Impossibilitar a exclusão de registros com outros registros associados

### ISSUE THREAD

**Issue by edvaldoszy** [utfpr/hcf-api#41]
## Overview

Hoje o sistema está permitindo que eu faça a exclusão de um registro de família que tenha subfamília associadas, o que não deve acontecer.

## Technical info

O painel hoje tem um botão de exclusão de um registro nas listagens de taxonomia, que pode ser usado mesmo em registros com outros registros associados.

Você deve fazer uma validação se o registro que está sendo excluído possui registros associados ou não (família e subfamília por exemplo) e retornar um error dizendo que a operação não pode ser realizada.

**Comment by RyanRamos01** [comment]
Lógicas adicionadas:

Dependentes de familia:

![Image](https://github.com/user-attachments/assets/a0acb2b1-4f8d-43e7-90ba-20d11786a912)

Dependentes de genero:

![Image](https://github.com/user-attachments/assets/6c70d9dd-be5b-4fe9-8f10-5e1af8c39c6f)

Dependentes de especie:

![Image](https://github.com/user-attachments/assets/0644cdba-ce2e-469e-956f-00df63989ebb)

Dependentes de autores:

![Image](https://github.com/user-attachments/assets/0c593dd1-2d8e-4711-9b4e-94f3be38b3bc)
